import { firaCode } from "@/constants";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={firaCode.className}>
        <div className='container mx-auto px-5 mt-10'>
          <nav className='flex justify-between items-center'>
            <p className='!m-0 font-semibold text-white text-xl'>
              faizer<span className='text-code-3'>.</span>shaikh
            </p>
            <ul className='flex justify-start items-center gap-6 font-fira-code text-text-color-2 font-medium'>
              <li className='cursor-pointer'>
                <span className='text-code-1'>[0]</span>:about me
              </li>
              <li className='cursor-pointer'>
                <span className='text-code-2'>[1]</span>:experience
              </li>
              <li className='cursor-pointer'>
                <span className='text-code-3'>[2]</span>:projects
              </li>
              <li className='cursor-pointer'>
                <span className='text-code-4'>[3]</span>:skills
              </li>
              <li className='cursor-pointer'>
                <span className='text-code-5'>[4]</span>:contact me
              </li>
            </ul>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
